version: '3.8'

services:
    db:
        image: postgres:12.4
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env
    
    web:
        build: .
        restart: always
        volumes:
            - static_value:/code/static/
            - media_value:/code/media/
        depends_on:
            - db
        env_file:
            - ./.env

    nginx:
        image: nginx:1.19.3
        restart: unless-stopped
        networks:
            nginx_net:
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_value:/var/html/static/
            - media_value:/var/html/media/
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        ports:
            - "80:80"
            - "443:443"
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
        depends_on:
            - web

    certbot:
        image: certbot/certbot
        restart: unless-stopped
        networks:
            nginx_net:
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    networks:
        nginx_net:
            name: nginx_net

volumes:
    postgres_data:
    static_value:
    media_value:
