# Generated by Django 3.2.2 on 2021-05-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='fon_style',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='Red', max_length=50, verbose_name='Цвет тега'),
        ),
        migrations.AddField(
            model_name='tag',
            name='display_name',
            field=models.CharField(default='Name', max_length=20, verbose_name='Имя тега в шаблоне'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(choices=[('Завтрак', 'breakfast'), ('Обед', 'lunch'), ('Ужин', 'dinner')], max_length=100, unique=True, verbose_name='Название тега'),
        ),
    ]
